[package]
name = "web_3d"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
tools = { path = "../tools" }